/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AmbulanceServiceSystem;

import java.awt.Color;
import java.io.File;
import javax.swing.JButton;
import javax.swing.JFileChooser;
import javax.swing.JPanel;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Hassan Nawaz
 */
public class CTWO_GUI extends javax.swing.JFrame {

    private JPanel panels[] = new JPanel[3];
    ASI inst=ASI.getInst();

    /**
     * Creates new form CTWO
     */
    public CTWO_GUI() {
        initComponents();
        jPanel3.setVisible(false);
        Minimize.setVisible(true);
        fillarr();
        selectedPanel(Dashboard);
       

    }

    public void changecolor(JButton hover, Color rand) {
        hover.setBackground(rand);
    }

    public void changecolor(JPanel hover, Color rand) {
        hover.setBackground(rand);
    }

    public void fillarr() {
        panels[0] = Dashboard;
//        panels[1] = Main_EMTs_Panel;
//        panels[2] = Main_Ambulance_Panel;
//        panels[3] = Main_Emergency_Panel;
//        panels[4] = Main_Parking_Panel;
//        panels[5] = Main_Driver_Panel;
        panels[1] = Account_CTWo_Main;
        panels[2] = ECF_FORM;
    }

//    public JTable stafftable()
//    {
//      return
//    }
    public void selectedPanel(JPanel panel) {
        for (JPanel panel1 : panels) {
            panel1.setVisible(false);
        }
        panel.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Dashboard = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        jPanel17 = new javax.swing.JPanel();
        jPanel18 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        Side_Menu_Main = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        database = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        login = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        logout = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        Dashboarbbutton = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        accountbutton = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        set1 = new javax.swing.JLabel();
        set2 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        ECF = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        Account_CTWo_Main = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel51 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jLabel52 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        upadte_Profile = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel53 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jLabel54 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        Update = new javax.swing.JButton();
        Minimize = new javax.swing.JPanel();
        exit2 = new javax.swing.JPanel();
        jLabel34 = new javax.swing.JLabel();
        mxmize2 = new javax.swing.JPanel();
        jLabel35 = new javax.swing.JLabel();
        minimize2 = new javax.swing.JPanel();
        jLabel36 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        ECF_FORM = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jTextField12 = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jTextField13 = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jTextField15 = new javax.swing.JTextField();
        jLabel39 = new javax.swing.JLabel();
        jTextField16 = new javax.swing.JTextField();
        jLabel40 = new javax.swing.JLabel();
        jTextField17 = new javax.swing.JTextField();
        jLabel41 = new javax.swing.JLabel();
        Apply_Button = new javax.swing.JButton();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel44 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox3 = new javax.swing.JComboBox<>();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        Apply_Button2 = new javax.swing.JButton();
        jTextField18 = new javax.swing.JTextField();
        jLabel47 = new javax.swing.JLabel();
        Apply_Button1 = new javax.swing.JButton();
        jTextField19 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(880, 540));
        setMinimumSize(new java.awt.Dimension(880, 540));
        setUndecorated(true);
        setSize(new java.awt.Dimension(880, 540));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Dashboard.setBackground(new java.awt.Color(26, 100, 162));
        Dashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DashboardMouseClicked(evt);
            }
        });
        Dashboard.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBackground(new java.awt.Color(255, 51, 51));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        Dashboard.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 20, 20));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        Dashboard.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 20, 20));

        jPanel8.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        Dashboard.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 20, 20));

        jPanel9.setBackground(new java.awt.Color(255, 51, 51));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        Dashboard.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));

        jPanel10.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        Dashboard.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 190, -1, -1));

        jPanel11.setBackground(new java.awt.Color(255, 51, 51));

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        Dashboard.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 190, -1, -1));

        jPanel12.setBackground(new java.awt.Color(255, 51, 51));

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        Dashboard.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 190, -1, -1));

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        Dashboard.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 350, -1, -1));

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        Dashboard.add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 350, -1, -1));

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        Dashboard.add(jPanel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 350, -1, -1));

        jPanel16.setBackground(new java.awt.Color(255, 51, 51));

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        Dashboard.add(jPanel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, -1, -1));

        jPanel17.setBackground(new java.awt.Color(255, 51, 51));

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        Dashboard.add(jPanel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 190, -1, -1));

        javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel18Layout.setVerticalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        Dashboard.add(jPanel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 350, -1, -1));

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("Damaged");
        Dashboard.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, -1, -1));

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("Free");
        Dashboard.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, -1, -1));

        jLabel37.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(255, 255, 255));
        jLabel37.setText("Occupied");
        Dashboard.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Parking");
        Dashboard.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 20, -1, -1));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8-parking-100.png"))); // NOI18N
        Dashboard.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 40, -1, -1));

        getContentPane().add(Dashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, 720, 510));

        Side_Menu_Main.setBackground(new java.awt.Color(49, 95, 240));
        Side_Menu_Main.setAutoscrolls(true);
        Side_Menu_Main.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(228, 228, 228));
        jPanel3.setPreferredSize(new java.awt.Dimension(84, 13));
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel3MouseClicked(evt);
            }
        });
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        database.setBackground(new java.awt.Color(228, 228, 228));
        database.setPreferredSize(new java.awt.Dimension(151, 47));
        database.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                databaseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                databaseMouseExited(evt);
            }
        });

        jLabel9.setBackground(new java.awt.Color(51, 51, 51));
        jLabel9.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 51, 51));
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8-help-25.png"))); // NOI18N

        jLabel29.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(51, 51, 51));
        jLabel29.setText("Help !");

        javax.swing.GroupLayout databaseLayout = new javax.swing.GroupLayout(database);
        database.setLayout(databaseLayout);
        databaseLayout.setHorizontalGroup(
            databaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(databaseLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        databaseLayout.setVerticalGroup(
            databaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel29, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        jPanel3.add(database, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, -1, 50));

        login.setBackground(new java.awt.Color(228, 228, 228));
        database.setPreferredSize(new java.awt.Dimension(151, 47));
        login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                loginMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                loginMouseExited(evt);
            }
        });

        jLabel8.setBackground(new java.awt.Color(51, 51, 51));
        jLabel8.setFont(new java.awt.Font("Trebuchet MS", 1, 10)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 51, 51));
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/user_30px.png"))); // NOI18N

        jLabel28.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(51, 51, 51));
        jLabel28.setText("Export The Report");

        javax.swing.GroupLayout loginLayout = new javax.swing.GroupLayout(login);
        login.setLayout(loginLayout);
        loginLayout.setHorizontalGroup(
            loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        loginLayout.setVerticalGroup(
            loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel28, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel3.add(login, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, -1, 50));

        logout.setBackground(new java.awt.Color(228, 228, 228));
        logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                logoutMouseExited(evt);
            }
        });

        jLabel10.setBackground(new java.awt.Color(51, 51, 51));
        jLabel10.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 51, 51));
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/exit_30px.png"))); // NOI18N

        jLabel30.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(51, 51, 51));
        jLabel30.setText("Logout");

        javax.swing.GroupLayout logoutLayout = new javax.swing.GroupLayout(logout);
        logout.setLayout(logoutLayout);
        logoutLayout.setHorizontalGroup(
            logoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logoutLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );
        logoutLayout.setVerticalGroup(
            logoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel30, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel3.add(logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 160, 40));

        Side_Menu_Main.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 150, 160));

        jLabel7.setForeground(new java.awt.Color(204, 204, 204));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/in_app_messaging_25px.png"))); // NOI18N
        jLabel7.setText("Exit");
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        jLabel7.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jLabel7KeyPressed(evt);
            }
        });
        Side_Menu_Main.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 500, 60, 30));

        jLabel24.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel24.setText("System");
        Side_Menu_Main.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, 50, 20));

        Dashboarbbutton.setBackground(new java.awt.Color(49, 95, 240));
        Dashboarbbutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DashboarbbuttonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                DashboarbbuttonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                DashboarbbuttonMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                DashboarbbuttonMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                DashboarbbuttonMouseReleased(evt);
            }
        });
        Dashboarbbutton.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/home_30px.png"))); // NOI18N
        jLabel5.setDebugGraphicsOptions(javax.swing.DebugGraphics.LOG_OPTION);
        Dashboarbbutton.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 140, 40));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Dashboard");
        Dashboarbbutton.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, -1, 30));

        Side_Menu_Main.add(Dashboarbbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 160, 50));

        accountbutton.setBackground(new java.awt.Color(49, 95, 240));
        accountbutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                accountbuttonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                accountbuttonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                accountbuttonMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                accountbuttonMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                accountbuttonMouseReleased(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/account_30px.png"))); // NOI18N

        jLabel6.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Account");

        javax.swing.GroupLayout accountbuttonLayout = new javax.swing.GroupLayout(accountbutton);
        accountbutton.setLayout(accountbuttonLayout);
        accountbuttonLayout.setHorizontalGroup(
            accountbuttonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(accountbuttonLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addContainerGap(48, Short.MAX_VALUE))
        );
        accountbuttonLayout.setVerticalGroup(
            accountbuttonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(accountbuttonLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(accountbuttonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        Side_Menu_Main.add(accountbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 160, 50));

        set1.setForeground(new java.awt.Color(204, 204, 204));
        set1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/settings_25px.png"))); // NOI18N
        set1.setText("Setting");
        set1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                set1MouseClicked(evt);
            }
        });
        Side_Menu_Main.add(set1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 500, 70, 30));

        set2.setForeground(new java.awt.Color(204, 204, 204));
        set2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/settings_25px.png"))); // NOI18N
        set2.setText("Setting");
        set2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                set2MouseClicked(evt);
            }
        });
        Side_Menu_Main.add(set2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 500, 70, 30));

        jLabel38.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel38.setText("Ambulance Service");
        Side_Menu_Main.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 110, 20));

        jLabel31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8-ambulance-25.png"))); // NOI18N
        Side_Menu_Main.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, 30));

        ECF.setBackground(new java.awt.Color(49, 95, 240));
        ECF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ECFMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ECFMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ECFMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ECFMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                ECFMouseReleased(evt);
            }
        });
        ECF.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8-google-forms-35.png"))); // NOI18N
        ECF.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 50, -1));

        jLabel15.setBackground(new java.awt.Color(204, 204, 204));
        jLabel15.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Fill ECF");
        ECF.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 80, 40));

        Side_Menu_Main.add(ECF, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 160, 50));

        getContentPane().add(Side_Menu_Main, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 160, 540));

        Account_CTWo_Main.setBackground(new java.awt.Color(26, 100, 162));
        Account_CTWo_Main.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Account Details");
        Account_CTWo_Main.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 50, 125, 25));

        jLabel18.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Full Name:");
        Account_CTWo_Main.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, -1, -1));

        jTextField5.setBackground(new java.awt.Color(26, 100, 162));
        jTextField5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jTextField5.setForeground(new java.awt.Color(102, 102, 102));
        jTextField5.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        jTextField5.setSelectionEnd(50);
        jTextField5.setSelectionStart(12);
        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });
        Account_CTWo_Main.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 215, -1));

        jLabel20.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("ID_Card:");
        Account_CTWo_Main.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, -1, -1));

        jTextField6.setBackground(new java.awt.Color(26, 100, 162));
        jTextField6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jTextField6.setForeground(new java.awt.Color(102, 102, 102));
        jTextField6.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        jTextField6.setSelectionEnd(50);
        jTextField6.setSelectionStart(12);
        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });
        Account_CTWo_Main.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 215, -1));

        jLabel22.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Contact No:");
        Account_CTWo_Main.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, -1, -1));

        jTextField7.setBackground(new java.awt.Color(26, 100, 162));
        jTextField7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jTextField7.setForeground(new java.awt.Color(102, 102, 102));
        jTextField7.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        jTextField7.setSelectionEnd(50);
        jTextField7.setSelectionStart(12);
        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });
        Account_CTWo_Main.add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, 215, -1));

        jLabel51.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel51.setForeground(new java.awt.Color(255, 255, 255));
        jLabel51.setText("Gender:");
        Account_CTWo_Main.add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, -1, -1));

        jTextField8.setBackground(new java.awt.Color(26, 100, 162));
        jTextField8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jTextField8.setForeground(new java.awt.Color(102, 102, 102));
        jTextField8.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        jTextField8.setSelectionEnd(50);
        jTextField8.setSelectionStart(12);
        jTextField8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField8ActionPerformed(evt);
            }
        });
        Account_CTWo_Main.add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, 215, -1));

        jLabel52.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel52.setForeground(new java.awt.Color(255, 255, 255));
        jLabel52.setText("Picture:");
        Account_CTWo_Main.add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 130, -1, -1));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 266, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 167, Short.MAX_VALUE)
        );

        Account_CTWo_Main.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 100, -1, -1));

        upadte_Profile.setBackground(new java.awt.Color(51, 51, 255));
        upadte_Profile.setForeground(new java.awt.Color(255, 255, 255));
        upadte_Profile.setText("Upade");
        upadte_Profile.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        upadte_Profile.setBorderPainted(false);
        upadte_Profile.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        upadte_Profile.setFocusPainted(false);
        upadte_Profile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                upadte_ProfileMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                upadte_ProfileMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                upadte_ProfileMouseExited(evt);
            }
        });
        upadte_Profile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                upadte_ProfileActionPerformed(evt);
            }
        });
        Account_CTWo_Main.add(upadte_Profile, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 420, 90, 30));

        jButton1.setBackground(new java.awt.Color(43, 43, 43));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Change");
        jButton1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.setBorderPainted(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setFocusPainted(false);
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton1MouseExited(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        Account_CTWo_Main.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 270, 90, 30));

        jLabel53.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel53.setForeground(new java.awt.Color(255, 255, 255));
        jLabel53.setText("Special ID:");
        Account_CTWo_Main.add(jLabel53, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, -1, -1));

        jTextField9.setBackground(new java.awt.Color(26, 100, 162));
        jTextField9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jTextField9.setForeground(new java.awt.Color(102, 102, 102));
        jTextField9.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        jTextField9.setSelectionEnd(50);
        jTextField9.setSelectionStart(12);
        jTextField9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField9ActionPerformed(evt);
            }
        });
        Account_CTWo_Main.add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 380, 198, -1));

        jLabel54.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel54.setForeground(new java.awt.Color(255, 255, 255));
        jLabel54.setText("Password:");
        Account_CTWo_Main.add(jLabel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 350, -1, -1));

        jTextField10.setBackground(new java.awt.Color(26, 100, 162));
        jTextField10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jTextField10.setForeground(new java.awt.Color(102, 102, 102));
        jTextField10.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        jTextField10.setSelectionEnd(50);
        jTextField10.setSelectionStart(12);
        jTextField10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField10ActionPerformed(evt);
            }
        });
        Account_CTWo_Main.add(jTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 370, 198, -1));

        Update.setBackground(new java.awt.Color(43, 43, 43));
        Update.setForeground(new java.awt.Color(255, 255, 255));
        Update.setText("Change");
        Update.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Update.setBorderPainted(false);
        Update.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Update.setFocusPainted(false);
        Update.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UpdateMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                UpdateMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                UpdateMouseExited(evt);
            }
        });
        Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateActionPerformed(evt);
            }
        });
        Account_CTWo_Main.add(Update, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 360, 63, 30));

        getContentPane().add(Account_CTWo_Main, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, 720, 510));

        Minimize.setBackground(new java.awt.Color(49, 95, 240));
        Minimize.setForeground(new java.awt.Color(52, 152, 219));
        Minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                MinimizejPanel11MouseEntered(evt);
            }
        });

        exit2.setBackground(new java.awt.Color(52, 152, 219));
        exit2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exit2exitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exit2exitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exit2exitMouseExited(evt);
            }
        });
        exit2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel34.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(255, 255, 255));
        jLabel34.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel34.setText("X");
        exit2.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 5, 30, 20));

        mxmize2.setBackground(new java.awt.Color(52, 152, 219));
        mxmize2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mxmize2mxmizeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mxmize2mxmizeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                mxmize2mxmizeMouseExited(evt);
            }
        });
        mxmize2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel35.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(255, 255, 255));
        jLabel35.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel35.setText("=");
        mxmize2.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 40, -1));

        minimize2.setBackground(new java.awt.Color(52, 152, 219));
        minimize2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimize2minimizeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                minimize2minimizeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                minimize2minimizeMouseExited(evt);
            }
        });

        jLabel36.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(255, 255, 255));
        jLabel36.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel36.setText("-");
        jLabel36.setToolTipText("-");

        javax.swing.GroupLayout minimize2Layout = new javax.swing.GroupLayout(minimize2);
        minimize2.setLayout(minimize2Layout);
        minimize2Layout.setHorizontalGroup(
            minimize2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(minimize2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel36, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
                .addContainerGap())
        );
        minimize2Layout.setVerticalGroup(
            minimize2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(minimize2Layout.createSequentialGroup()
                .addComponent(jLabel36, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel12.setBackground(new java.awt.Color(156, 156, 156));
        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setText("Dashboard");

        javax.swing.GroupLayout MinimizeLayout = new javax.swing.GroupLayout(Minimize);
        Minimize.setLayout(MinimizeLayout);
        MinimizeLayout.setHorizontalGroup(
            MinimizeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MinimizeLayout.createSequentialGroup()
                .addGap(259, 259, 259)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 267, Short.MAX_VALUE)
                .addComponent(minimize2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(mxmize2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(exit2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        MinimizeLayout.setVerticalGroup(
            MinimizeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(minimize2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MinimizeLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel12))
            .addGroup(MinimizeLayout.createSequentialGroup()
                .addGroup(MinimizeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mxmize2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(exit2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(Minimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 0, 720, 30));

        ECF_FORM.setBackground(new java.awt.Color(26, 100, 162));
        ECF_FORM.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel19.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Fill The ECF");
        ECF_FORM.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 20, -1, -1));

        jTextField11.setBackground(new java.awt.Color(26, 100, 162));
        jTextField11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jTextField11.setForeground(new java.awt.Color(255, 255, 255));
        jTextField11.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        jTextField11.setSelectionEnd(50);
        jTextField11.setSelectionStart(12);
        jTextField11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField11ActionPerformed(evt);
            }
        });
        ECF_FORM.add(jTextField11, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, 215, -1));

        jLabel21.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Realtion With Patient");
        ECF_FORM.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, -1, -1));

        jTextField12.setBackground(new java.awt.Color(26, 100, 162));
        jTextField12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jTextField12.setForeground(new java.awt.Color(255, 255, 255));
        jTextField12.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        jTextField12.setSelectionEnd(50);
        jTextField12.setSelectionStart(12);
        jTextField12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField12ActionPerformed(evt);
            }
        });
        ECF_FORM.add(jTextField12, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, 215, -1));

        jLabel23.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Contact No:");
        ECF_FORM.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, -1, -1));

        jTextField13.setBackground(new java.awt.Color(26, 100, 162));
        jTextField13.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jTextField13.setForeground(new java.awt.Color(255, 255, 255));
        jTextField13.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        jTextField13.setSelectionEnd(50);
        jTextField13.setSelectionStart(12);
        jTextField13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField13ActionPerformed(evt);
            }
        });
        ECF_FORM.add(jTextField13, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 240, 215, -1));

        jLabel26.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("Availabel Ambulance");
        ECF_FORM.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 350, -1, -1));

        jLabel32.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setText("Dispatch Ambulance");
        ECF_FORM.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 320, -1, -1));

        jLabel33.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(255, 255, 255));
        jLabel33.setText("Emergency Nature");
        ECF_FORM.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 100, -1, -1));

        jTextField15.setBackground(new java.awt.Color(26, 100, 162));
        jTextField15.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jTextField15.setForeground(new java.awt.Color(255, 255, 255));
        jTextField15.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        jTextField15.setSelectionEnd(50);
        jTextField15.setSelectionStart(12);
        jTextField15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField15ActionPerformed(evt);
            }
        });
        ECF_FORM.add(jTextField15, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 120, 215, -1));

        jLabel39.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(255, 255, 255));
        jLabel39.setText("Location");
        ECF_FORM.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 160, -1, -1));

        jTextField16.setBackground(new java.awt.Color(26, 100, 162));
        jTextField16.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jTextField16.setForeground(new java.awt.Color(255, 255, 255));
        jTextField16.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        jTextField16.setSelectionEnd(50);
        jTextField16.setSelectionStart(12);
        jTextField16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField16ActionPerformed(evt);
            }
        });
        ECF_FORM.add(jTextField16, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 180, 215, -1));

        jLabel40.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(255, 255, 255));
        jLabel40.setText("Date");
        ECF_FORM.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 220, -1, -1));

        jTextField17.setBackground(new java.awt.Color(26, 100, 162));
        jTextField17.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jTextField17.setForeground(new java.awt.Color(255, 255, 255));
        jTextField17.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        jTextField17.setSelectionEnd(50);
        jTextField17.setSelectionStart(12);
        jTextField17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField17ActionPerformed(evt);
            }
        });
        ECF_FORM.add(jTextField17, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 430, 215, -1));

        jLabel41.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(255, 255, 255));
        jLabel41.setText("Emergency Detail");
        ECF_FORM.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 60, -1, -1));

        Apply_Button.setBackground(new java.awt.Color(51, 51, 255));
        Apply_Button.setForeground(new java.awt.Color(255, 255, 255));
        Apply_Button.setText("Dispatch");
        Apply_Button.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Apply_Button.setBorderPainted(false);
        Apply_Button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Apply_Button.setFocusPainted(false);
        Apply_Button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Apply_ButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Apply_ButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Apply_ButtonMouseExited(evt);
            }
        });
        Apply_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Apply_ButtonActionPerformed(evt);
            }
        });
        ECF_FORM.add(Apply_Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 470, 80, 30));

        jLabel42.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(255, 255, 255));
        jLabel42.setText("Caller Detail");
        ECF_FORM.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, -1, -1));

        jLabel43.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel43.setForeground(new java.awt.Color(255, 255, 255));
        jLabel43.setText("Full Name:");
        ECF_FORM.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, -1, -1));

        jComboBox1.setBackground(new java.awt.Color(26, 100, 162));
        jComboBox1.setForeground(new java.awt.Color(255, 255, 255));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ahmed", "Nazeer" }));
        ECF_FORM.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 430, 220, -1));

        jLabel44.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel44.setForeground(new java.awt.Color(255, 255, 255));
        jLabel44.setText("Available Drivers");
        ECF_FORM.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 410, -1, -1));

        jComboBox2.setBackground(new java.awt.Color(26, 100, 162));
        jComboBox2.setForeground(new java.awt.Color(255, 255, 255));
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pair 1", "Pair 2" }));
        ECF_FORM.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 380, 220, -1));

        jComboBox3.setBackground(new java.awt.Color(26, 100, 162));
        jComboBox3.setForeground(new java.awt.Color(255, 255, 255));
        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ambulance 1", "Ambulance 2" }));
        ECF_FORM.add(jComboBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 380, 220, -1));

        jLabel45.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel45.setForeground(new java.awt.Color(255, 255, 255));
        jLabel45.setText("Available EMTs");
        ECF_FORM.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 350, -1, -1));

        jLabel46.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel46.setForeground(new java.awt.Color(255, 255, 255));
        jLabel46.setText("Near Hospital");
        ECF_FORM.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 410, -1, -1));

        Apply_Button2.setBackground(new java.awt.Color(51, 51, 255));
        Apply_Button2.setForeground(new java.awt.Color(255, 255, 255));
        Apply_Button2.setText("Decline");
        Apply_Button2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Apply_Button2.setBorderPainted(false);
        Apply_Button2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Apply_Button2.setFocusPainted(false);
        Apply_Button2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Apply_Button2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Apply_Button2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Apply_Button2MouseExited(evt);
            }
        });
        Apply_Button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Apply_Button2ActionPerformed(evt);
            }
        });
        ECF_FORM.add(Apply_Button2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 470, 80, 30));

        jTextField18.setBackground(new java.awt.Color(26, 100, 162));
        jTextField18.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jTextField18.setForeground(new java.awt.Color(255, 255, 255));
        jTextField18.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        jTextField18.setSelectionEnd(50);
        jTextField18.setSelectionStart(12);
        jTextField18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField18ActionPerformed(evt);
            }
        });
        ECF_FORM.add(jTextField18, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 290, 215, -1));

        jLabel47.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel47.setForeground(new java.awt.Color(255, 255, 255));
        jLabel47.setText("Duration");
        ECF_FORM.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 270, -1, -1));

        Apply_Button1.setBackground(new java.awt.Color(51, 51, 255));
        Apply_Button1.setForeground(new java.awt.Color(255, 255, 255));
        Apply_Button1.setText("Open Map");
        Apply_Button1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Apply_Button1.setBorderPainted(false);
        Apply_Button1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Apply_Button1.setFocusPainted(false);
        Apply_Button1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Apply_Button1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Apply_Button1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Apply_Button1MouseExited(evt);
            }
        });
        Apply_Button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Apply_Button1ActionPerformed(evt);
            }
        });
        ECF_FORM.add(Apply_Button1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 150, 80, 30));

        jTextField19.setBackground(new java.awt.Color(26, 100, 162));
        jTextField19.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jTextField19.setForeground(new java.awt.Color(255, 255, 255));
        jTextField19.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        jTextField19.setSelectionEnd(50);
        jTextField19.setSelectionStart(12);
        jTextField19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField19ActionPerformed(evt);
            }
        });
        ECF_FORM.add(jTextField19, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 240, 215, -1));

        getContentPane().add(ECF_FORM, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, 720, 510));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void databaseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_databaseMouseEntered
        changecolor(database, new Color(69, 73, 74));
    }//GEN-LAST:event_databaseMouseEntered

    private void databaseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_databaseMouseExited
        changecolor(database, new Color(228, 228, 228));
    }//GEN-LAST:event_databaseMouseExited

    private void loginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginMouseClicked

    }//GEN-LAST:event_loginMouseClicked

    private void loginMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginMouseEntered
        changecolor(login, new Color(69, 73, 74));
    }//GEN-LAST:event_loginMouseEntered

    private void loginMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginMouseExited
        changecolor(login, new Color(228, 228, 228));
    }//GEN-LAST:event_loginMouseExited

    private void logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseClicked
        this.setVisible(false);
        new Login().setVisible(true);
    }//GEN-LAST:event_logoutMouseClicked

    private void logoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseEntered
        changecolor(logout, new Color(69, 73, 74));
    }//GEN-LAST:event_logoutMouseEntered

    private void logoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseExited
        changecolor(logout, new Color(228, 228, 228));
    }//GEN-LAST:event_logoutMouseExited

    private void jPanel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseClicked
        // TODO add your handling code here:
        jPanel3.setVisible(false);
    }//GEN-LAST:event_jPanel3MouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jLabel7KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jLabel7KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel7KeyPressed

    private void DashboarbbuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DashboarbbuttonMouseClicked
        
        selectedPanel(Dashboard);
        jLabel12.setText("Dashboard");
    }//GEN-LAST:event_DashboarbbuttonMouseClicked

    private void DashboarbbuttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DashboarbbuttonMouseEntered
        changecolor(Dashboarbbutton, new Color(69, 73, 74));
    }//GEN-LAST:event_DashboarbbuttonMouseEntered

    private void DashboarbbuttonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DashboarbbuttonMouseExited
        changecolor(Dashboarbbutton, new Color(49, 95, 240));
    }//GEN-LAST:event_DashboarbbuttonMouseExited

    private void DashboarbbuttonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DashboarbbuttonMousePressed
        changecolor(Dashboarbbutton, new Color(234, 172, 84));
    }//GEN-LAST:event_DashboarbbuttonMousePressed

    private void DashboarbbuttonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DashboarbbuttonMouseReleased
        changecolor(Dashboarbbutton, new Color(69, 73, 74));
    }//GEN-LAST:event_DashboarbbuttonMouseReleased

    private void accountbuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_accountbuttonMouseClicked
        
        selectedPanel(Account_CTWo_Main);
        jLabel12.setText("Account");
    }//GEN-LAST:event_accountbuttonMouseClicked

    private void accountbuttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_accountbuttonMouseEntered
        changecolor(accountbutton, new Color(69, 73, 74));
    }//GEN-LAST:event_accountbuttonMouseEntered

    private void accountbuttonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_accountbuttonMouseExited
        changecolor(accountbutton, new Color(49, 95, 240));
    }//GEN-LAST:event_accountbuttonMouseExited

    private void accountbuttonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_accountbuttonMousePressed
        changecolor(accountbutton, new Color(234, 172, 84));
    }//GEN-LAST:event_accountbuttonMousePressed

    private void accountbuttonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_accountbuttonMouseReleased
        changecolor(accountbutton, new Color(69, 73, 74));
    }//GEN-LAST:event_accountbuttonMouseReleased

    private void set1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_set1MouseClicked
        // TODO add your handling code here:
        jPanel3.setEnabled(true);
        jPanel3.setVisible(true);
        set2.setEnabled(true);
        set2.setVisible(true);
        set1.setEnabled(false);
        set1.setVisible(false);
    }//GEN-LAST:event_set1MouseClicked

    private void set2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_set2MouseClicked
        // TODO add your handling code here:
        jPanel3.setEnabled(false);
        jPanel3.setVisible(false);
        set1.setEnabled(true);
        set1.setVisible(true);
        set2.setEnabled(false);
        set2.setVisible(false);
    }//GEN-LAST:event_set2MouseClicked

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7ActionPerformed

    private void jTextField8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField8ActionPerformed

    private void upadte_ProfileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_upadte_ProfileMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_upadte_ProfileMouseClicked

    private void upadte_ProfileMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_upadte_ProfileMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_upadte_ProfileMouseEntered

    private void upadte_ProfileMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_upadte_ProfileMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_upadte_ProfileMouseExited

    private void upadte_ProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_upadte_ProfileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_upadte_ProfileActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked

    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseEntered
        changecolor(jButton1, new Color(255, 51, 153));
    }//GEN-LAST:event_jButton1MouseEntered

    private void jButton1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseExited
        changecolor(jButton1, new Color(43, 43, 43));
    }//GEN-LAST:event_jButton1MouseExited

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        JFileChooser file = new JFileChooser();
        file.setCurrentDirectory(new File("user.dir"));
        FileNameExtensionFilter filter = new FileNameExtensionFilter("All Type", "jpg", "png", "jpeg", "gif");
        file.addChoosableFileFilter(filter);
        file.showSaveDialog(null);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField9ActionPerformed

    private void jTextField10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField10ActionPerformed

    private void UpdateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UpdateMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_UpdateMouseClicked

    private void UpdateMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UpdateMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_UpdateMouseEntered

    private void UpdateMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UpdateMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_UpdateMouseExited

    private void UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UpdateActionPerformed

    private void DashboardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DashboardMouseClicked

    }//GEN-LAST:event_DashboardMouseClicked

    private void exit2exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exit2exitMouseClicked
        System.exit(0);
    }//GEN-LAST:event_exit2exitMouseClicked

    private void exit2exitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exit2exitMouseEntered
        changecolor(exit2, new Color(69, 73, 74));
    }//GEN-LAST:event_exit2exitMouseEntered

    private void exit2exitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exit2exitMouseExited
        changecolor(exit2, new Color(52, 152, 219));
    }//GEN-LAST:event_exit2exitMouseExited

    private void mxmize2mxmizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mxmize2mxmizeMouseClicked

        //   if (this.getExtendedState() != ASI_GUI.MAXIMIZED_BOTH) {
        //       this.setExtendedState(ASI_GUI.MAXIMIZED_BOTH);
        //   } else {
        //      this.setExtendedState(ASI_GUI.NORMAL);
        //  }
    }//GEN-LAST:event_mxmize2mxmizeMouseClicked

    private void mxmize2mxmizeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mxmize2mxmizeMouseEntered
        changecolor(mxmize2, new Color(69, 73, 74));
    }//GEN-LAST:event_mxmize2mxmizeMouseEntered

    private void mxmize2mxmizeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mxmize2mxmizeMouseExited
        changecolor(mxmize2, new Color(52, 152, 219));
    }//GEN-LAST:event_mxmize2mxmizeMouseExited

    private void minimize2minimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimize2minimizeMouseClicked
        // TODO add your handling code here:
        if (this.getExtendedState() != ASI_GUI.ICONIFIED) {
            this.setExtendedState(ASI_GUI.ICONIFIED);
        } else {
            this.setExtendedState(ASI_GUI.NORMAL);
        }
    }//GEN-LAST:event_minimize2minimizeMouseClicked

    private void minimize2minimizeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimize2minimizeMouseEntered
        changecolor(minimize2, new Color(69, 73, 74));
    }//GEN-LAST:event_minimize2minimizeMouseEntered

    private void minimize2minimizeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimize2minimizeMouseExited
        changecolor(minimize2, new Color(52, 152, 219));
    }//GEN-LAST:event_minimize2minimizeMouseExited

    private void MinimizejPanel11MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinimizejPanel11MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_MinimizejPanel11MouseEntered

    private void ECFMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ECFMouseEntered
        changecolor(ECF, new Color(69, 73, 74));
    }//GEN-LAST:event_ECFMouseEntered

    private void ECFMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ECFMouseExited
        changecolor(ECF, new Color(49, 95, 240));
    }//GEN-LAST:event_ECFMouseExited

    private void ECFMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ECFMousePressed
        changecolor(ECF, new Color(234, 172, 84));
    }//GEN-LAST:event_ECFMousePressed

    private void ECFMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ECFMouseReleased
        changecolor(ECF, new Color(69, 73, 74));
    }//GEN-LAST:event_ECFMouseReleased

    private void ECFMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ECFMouseClicked
        
        selectedPanel(ECF_FORM);
        jLabel12.setText("ECF");
    }//GEN-LAST:event_ECFMouseClicked

    private void jTextField11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField11ActionPerformed

    private void jTextField12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField12ActionPerformed

    private void jTextField13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField13ActionPerformed

    private void jTextField15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField15ActionPerformed

    private void jTextField16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField16ActionPerformed

    private void jTextField17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField17ActionPerformed

    private void Apply_ButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Apply_ButtonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_Apply_ButtonMouseClicked

    private void Apply_ButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Apply_ButtonMouseEntered
        changecolor(Apply_Button, new Color(43, 43, 43));
    }//GEN-LAST:event_Apply_ButtonMouseEntered

    private void Apply_ButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Apply_ButtonMouseExited
        changecolor(Apply_Button, new Color(51, 51, 255));
    }//GEN-LAST:event_Apply_ButtonMouseExited

    private void Apply_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Apply_ButtonActionPerformed
       String name=jTextField11.getText();
       String relation=jTextField12.getText();
       String contact_number=jTextField13.getText();
       String duration=jTextField18.getText();
       Caller_Class caller=new Caller_Class(name, contact_number, relation, duration);
       String emergency_detail=jTextField15.getText();
       String location=jTextField16.getText();
       String date=jTextField19.getText();

    }//GEN-LAST:event_Apply_ButtonActionPerformed

    private void Apply_Button2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Apply_Button2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_Apply_Button2MouseClicked

    private void Apply_Button2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Apply_Button2MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_Apply_Button2MouseEntered

    private void Apply_Button2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Apply_Button2MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_Apply_Button2MouseExited

    private void Apply_Button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Apply_Button2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Apply_Button2ActionPerformed

    private void jTextField18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField18ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField18ActionPerformed

    private void Apply_Button1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Apply_Button1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_Apply_Button1MouseClicked

    private void Apply_Button1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Apply_Button1MouseEntered
        changecolor(Apply_Button, new Color(43, 43, 43));
    }//GEN-LAST:event_Apply_Button1MouseEntered

    private void Apply_Button1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Apply_Button1MouseExited
        changecolor(Apply_Button, new Color(51, 51, 255));
    }//GEN-LAST:event_Apply_Button1MouseExited

    private void Apply_Button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Apply_Button1ActionPerformed
       new Google_Map().setVisible(true);        

    }//GEN-LAST:event_Apply_Button1ActionPerformed

    private void jTextField19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField19ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField19ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CTWO_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CTWO_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CTWO_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CTWO_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CTWO_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Account_CTWo_Main;
    private javax.swing.JButton Apply_Button;
    private javax.swing.JButton Apply_Button1;
    private javax.swing.JButton Apply_Button2;
    private javax.swing.JPanel Dashboarbbutton;
    private javax.swing.JPanel Dashboard;
    private javax.swing.JPanel ECF;
    private javax.swing.JPanel ECF_FORM;
    private javax.swing.JPanel Minimize;
    private javax.swing.JPanel Side_Menu_Main;
    private javax.swing.JButton Update;
    private javax.swing.JPanel accountbutton;
    private javax.swing.JPanel database;
    private javax.swing.JPanel exit2;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField jTextField18;
    private javax.swing.JTextField jTextField19;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JPanel login;
    private javax.swing.JPanel logout;
    private javax.swing.JPanel minimize2;
    private javax.swing.JPanel mxmize2;
    private javax.swing.JLabel set1;
    private javax.swing.JLabel set2;
    private javax.swing.JButton upadte_Profile;
    // End of variables declaration//GEN-END:variables
}
