/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AmbulanceServiceSystem;

import java.awt.Color;
import javax.swing.JButton;
import javax.swing.JPanel;

/**
 *
 * @author Hassan Nawaz
 */
public class Emergency_Detail extends javax.swing.JFrame {

    /**
     * Creates new form Emergency_Detail
     */
    public Emergency_Detail() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        exit2 = new javax.swing.JPanel();
        jLabel34 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        name_apply7 = new javax.swing.JTextField();
        jLabel58 = new javax.swing.JLabel();
        name_apply8 = new javax.swing.JTextField();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        name_apply9 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        name_apply3 = new javax.swing.JTextField();
        jLabel60 = new javax.swing.JLabel();
        name_apply4 = new javax.swing.JTextField();
        jLabel61 = new javax.swing.JLabel();
        name_apply5 = new javax.swing.JTextField();
        jLabel62 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel63 = new javax.swing.JLabel();
        name_apply10 = new javax.swing.JTextField();
        jLabel64 = new javax.swing.JLabel();
        name_apply11 = new javax.swing.JTextField();
        jLabel65 = new javax.swing.JLabel();
        name_apply12 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel66 = new javax.swing.JLabel();
        name_apply13 = new javax.swing.JTextField();
        name_apply14 = new javax.swing.JTextField();
        jLabel67 = new javax.swing.JLabel();
        jLabel68 = new javax.swing.JLabel();
        name_apply15 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel69 = new javax.swing.JLabel();
        name_apply16 = new javax.swing.JTextField();
        name_apply17 = new javax.swing.JTextField();
        name_apply18 = new javax.swing.JTextField();
        jLabel70 = new javax.swing.JLabel();
        name_apply19 = new javax.swing.JTextField();
        name_apply20 = new javax.swing.JTextField();
        jLabel71 = new javax.swing.JLabel();
        jLabel72 = new javax.swing.JLabel();
        name_apply21 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(26, 100, 162));
        setMaximumSize(new java.awt.Dimension(720, 510));
        setMinimumSize(new java.awt.Dimension(720, 510));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(26, 100, 162));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        exit2.setBackground(new java.awt.Color(52, 152, 219));
        exit2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exit2exitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exit2exitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exit2exitMouseExited(evt);
            }
        });
        exit2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel34.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(255, 255, 255));
        jLabel34.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel34.setText("X");
        exit2.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 30, 30));

        jPanel1.add(exit2, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 0, 30, 30));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Other Information");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 280, -1, -1));

        jLabel44.setBackground(new java.awt.Color(102, 102, 255));
        jLabel44.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel44.setForeground(new java.awt.Color(255, 255, 255));
        jLabel44.setText("ID Card");
        jPanel1.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, 20));

        name_apply7.setEditable(false);
        name_apply7.setBackground(new java.awt.Color(26, 100, 162));
        name_apply7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        name_apply7.setForeground(new java.awt.Color(255, 255, 255));
        name_apply7.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        name_apply7.setSelectionEnd(50);
        name_apply7.setSelectionStart(12);
        name_apply7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                name_apply7ActionPerformed(evt);
            }
        });
        jPanel1.add(name_apply7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 180, -1));

        jLabel58.setBackground(new java.awt.Color(102, 102, 255));
        jLabel58.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel58.setForeground(new java.awt.Color(255, 255, 255));
        jLabel58.setText("Full Name");
        jPanel1.add(jLabel58, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, 20));

        name_apply8.setEditable(false);
        name_apply8.setBackground(new java.awt.Color(26, 100, 162));
        name_apply8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        name_apply8.setForeground(new java.awt.Color(255, 255, 255));
        name_apply8.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        name_apply8.setSelectionEnd(50);
        name_apply8.setSelectionStart(12);
        name_apply8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                name_apply8ActionPerformed(evt);
            }
        });
        jPanel1.add(name_apply8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 180, -1));

        jLabel45.setBackground(new java.awt.Color(102, 102, 255));
        jLabel45.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel45.setForeground(new java.awt.Color(255, 255, 255));
        jLabel45.setText("Gender");
        jPanel1.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, 20));

        jLabel46.setBackground(new java.awt.Color(102, 102, 255));
        jLabel46.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel46.setForeground(new java.awt.Color(255, 255, 255));
        jLabel46.setText("Contact Number");
        jPanel1.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, 20));

        name_apply9.setEditable(false);
        name_apply9.setBackground(new java.awt.Color(26, 100, 162));
        name_apply9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        name_apply9.setForeground(new java.awt.Color(255, 255, 255));
        name_apply9.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        name_apply9.setSelectionEnd(50);
        name_apply9.setSelectionStart(12);
        name_apply9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                name_apply9ActionPerformed(evt);
            }
        });
        jPanel1.add(name_apply9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 180, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Caller Detail");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 240, -1, -1));

        jLabel59.setBackground(new java.awt.Color(102, 102, 255));
        jLabel59.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel59.setForeground(new java.awt.Color(255, 255, 255));
        jLabel59.setText("Hospital Alloted");
        jPanel1.add(jLabel59, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, -1, 20));

        name_apply3.setEditable(false);
        name_apply3.setBackground(new java.awt.Color(26, 100, 162));
        name_apply3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        name_apply3.setForeground(new java.awt.Color(255, 255, 255));
        name_apply3.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        name_apply3.setSelectionEnd(50);
        name_apply3.setSelectionStart(12);
        name_apply3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                name_apply3ActionPerformed(evt);
            }
        });
        jPanel1.add(name_apply3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 180, -1));

        jLabel60.setBackground(new java.awt.Color(102, 102, 255));
        jLabel60.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel60.setForeground(new java.awt.Color(255, 255, 255));
        jLabel60.setText("Room Number");
        jPanel1.add(jLabel60, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, -1, 20));

        name_apply4.setEditable(false);
        name_apply4.setBackground(new java.awt.Color(26, 100, 162));
        name_apply4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        name_apply4.setForeground(new java.awt.Color(255, 255, 255));
        name_apply4.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        name_apply4.setSelectionEnd(50);
        name_apply4.setSelectionStart(12);
        name_apply4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                name_apply4ActionPerformed(evt);
            }
        });
        jPanel1.add(name_apply4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, 180, -1));

        jLabel61.setBackground(new java.awt.Color(102, 102, 255));
        jLabel61.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel61.setForeground(new java.awt.Color(255, 255, 255));
        jLabel61.setText("Bed Number");
        jPanel1.add(jLabel61, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, -1, 20));

        name_apply5.setEditable(false);
        name_apply5.setBackground(new java.awt.Color(26, 100, 162));
        name_apply5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        name_apply5.setForeground(new java.awt.Color(255, 255, 255));
        name_apply5.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        name_apply5.setSelectionEnd(50);
        name_apply5.setSelectionStart(12);
        name_apply5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                name_apply5ActionPerformed(evt);
            }
        });
        jPanel1.add(name_apply5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 450, 180, -1));

        jLabel62.setBackground(new java.awt.Color(102, 102, 255));
        jLabel62.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel62.setForeground(new java.awt.Color(255, 255, 255));
        jLabel62.setText("Emergency Nature");
        jPanel1.add(jLabel62, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 70, -1, 20));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Patient Detail");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        jLabel63.setBackground(new java.awt.Color(102, 102, 255));
        jLabel63.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel63.setForeground(new java.awt.Color(255, 255, 255));
        jLabel63.setText("Location");
        jPanel1.add(jLabel63, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 120, -1, 20));

        name_apply10.setEditable(false);
        name_apply10.setBackground(new java.awt.Color(26, 100, 162));
        name_apply10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        name_apply10.setForeground(new java.awt.Color(255, 255, 255));
        name_apply10.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        name_apply10.setSelectionEnd(50);
        name_apply10.setSelectionStart(12);
        name_apply10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                name_apply10ActionPerformed(evt);
            }
        });
        jPanel1.add(name_apply10, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 140, 180, -1));

        jLabel64.setBackground(new java.awt.Color(102, 102, 255));
        jLabel64.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel64.setForeground(new java.awt.Color(255, 255, 255));
        jLabel64.setText("Emergency Code");
        jPanel1.add(jLabel64, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 170, -1, 20));

        name_apply11.setEditable(false);
        name_apply11.setBackground(new java.awt.Color(26, 100, 162));
        name_apply11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        name_apply11.setForeground(new java.awt.Color(255, 255, 255));
        name_apply11.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        name_apply11.setSelectionEnd(50);
        name_apply11.setSelectionStart(12);
        name_apply11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                name_apply11ActionPerformed(evt);
            }
        });
        jPanel1.add(name_apply11, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 190, 180, -1));

        jLabel65.setBackground(new java.awt.Color(102, 102, 255));
        jLabel65.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel65.setForeground(new java.awt.Color(255, 255, 255));
        jLabel65.setText("Date");
        jPanel1.add(jLabel65, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 220, -1, 20));

        name_apply12.setEditable(false);
        name_apply12.setBackground(new java.awt.Color(26, 100, 162));
        name_apply12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        name_apply12.setForeground(new java.awt.Color(255, 255, 255));
        name_apply12.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        name_apply12.setSelectionEnd(50);
        name_apply12.setSelectionStart(12);
        name_apply12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                name_apply12ActionPerformed(evt);
            }
        });
        jPanel1.add(name_apply12, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 240, 180, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Hospital Detail");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, -1, -1));

        jLabel66.setBackground(new java.awt.Color(102, 102, 255));
        jLabel66.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel66.setForeground(new java.awt.Color(255, 255, 255));
        jLabel66.setText("Ambulance Number");
        jPanel1.add(jLabel66, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 320, -1, 20));

        name_apply13.setEditable(false);
        name_apply13.setBackground(new java.awt.Color(26, 100, 162));
        name_apply13.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        name_apply13.setForeground(new java.awt.Color(255, 255, 255));
        name_apply13.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        name_apply13.setSelectionEnd(50);
        name_apply13.setSelectionStart(12);
        name_apply13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                name_apply13ActionPerformed(evt);
            }
        });
        jPanel1.add(name_apply13, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 340, 180, -1));

        name_apply14.setEditable(false);
        name_apply14.setBackground(new java.awt.Color(26, 100, 162));
        name_apply14.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        name_apply14.setForeground(new java.awt.Color(255, 255, 255));
        name_apply14.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        name_apply14.setSelectionEnd(50);
        name_apply14.setSelectionStart(12);
        name_apply14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                name_apply14ActionPerformed(evt);
            }
        });
        jPanel1.add(name_apply14, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 390, 180, -1));

        jLabel67.setBackground(new java.awt.Color(102, 102, 255));
        jLabel67.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel67.setForeground(new java.awt.Color(255, 255, 255));
        jLabel67.setText("Driver");
        jPanel1.add(jLabel67, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 370, -1, 20));

        jLabel68.setBackground(new java.awt.Color(102, 102, 255));
        jLabel68.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel68.setForeground(new java.awt.Color(255, 255, 255));
        jLabel68.setText("EMTs");
        jPanel1.add(jLabel68, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 430, -1, 20));

        name_apply15.setEditable(false);
        name_apply15.setBackground(new java.awt.Color(26, 100, 162));
        name_apply15.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        name_apply15.setForeground(new java.awt.Color(255, 255, 255));
        name_apply15.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        name_apply15.setSelectionEnd(50);
        name_apply15.setSelectionStart(12);
        name_apply15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                name_apply15ActionPerformed(evt);
            }
        });
        jPanel1.add(name_apply15, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 450, 180, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Patient Picture");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(495, 30, 150, -1));

        jLabel69.setBackground(new java.awt.Color(102, 102, 255));
        jLabel69.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel69.setForeground(new java.awt.Color(255, 255, 255));
        jLabel69.setText("Name");
        jPanel1.add(jLabel69, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 280, -1, 20));

        name_apply16.setEditable(false);
        name_apply16.setBackground(new java.awt.Color(26, 100, 162));
        name_apply16.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        name_apply16.setForeground(new java.awt.Color(255, 255, 255));
        name_apply16.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        name_apply16.setSelectionEnd(50);
        name_apply16.setSelectionStart(12);
        name_apply16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                name_apply16ActionPerformed(evt);
            }
        });
        jPanel1.add(name_apply16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 180, -1));

        name_apply17.setEditable(false);
        name_apply17.setBackground(new java.awt.Color(26, 100, 162));
        name_apply17.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        name_apply17.setForeground(new java.awt.Color(255, 255, 255));
        name_apply17.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        name_apply17.setSelectionEnd(50);
        name_apply17.setSelectionStart(12);
        name_apply17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                name_apply17ActionPerformed(evt);
            }
        });
        jPanel1.add(name_apply17, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 300, 180, -1));

        name_apply18.setEditable(false);
        name_apply18.setBackground(new java.awt.Color(26, 100, 162));
        name_apply18.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        name_apply18.setForeground(new java.awt.Color(255, 255, 255));
        name_apply18.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        name_apply18.setSelectionEnd(50);
        name_apply18.setSelectionStart(12);
        name_apply18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                name_apply18ActionPerformed(evt);
            }
        });
        jPanel1.add(name_apply18, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 90, 180, -1));

        jLabel70.setBackground(new java.awt.Color(102, 102, 255));
        jLabel70.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel70.setForeground(new java.awt.Color(255, 255, 255));
        jLabel70.setText("Relation With Patient");
        jPanel1.add(jLabel70, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 330, -1, 20));

        name_apply19.setEditable(false);
        name_apply19.setBackground(new java.awt.Color(26, 100, 162));
        name_apply19.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        name_apply19.setForeground(new java.awt.Color(255, 255, 255));
        name_apply19.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        name_apply19.setSelectionEnd(50);
        name_apply19.setSelectionStart(12);
        name_apply19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                name_apply19ActionPerformed(evt);
            }
        });
        jPanel1.add(name_apply19, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 350, 180, -1));

        name_apply20.setEditable(false);
        name_apply20.setBackground(new java.awt.Color(26, 100, 162));
        name_apply20.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        name_apply20.setForeground(new java.awt.Color(255, 255, 255));
        name_apply20.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        name_apply20.setSelectionEnd(50);
        name_apply20.setSelectionStart(12);
        name_apply20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                name_apply20ActionPerformed(evt);
            }
        });
        jPanel1.add(name_apply20, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 400, 180, -1));

        jLabel71.setBackground(new java.awt.Color(102, 102, 255));
        jLabel71.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel71.setForeground(new java.awt.Color(255, 255, 255));
        jLabel71.setText("Contact Number");
        jPanel1.add(jLabel71, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 380, -1, 20));

        jLabel72.setBackground(new java.awt.Color(102, 102, 255));
        jLabel72.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel72.setForeground(new java.awt.Color(255, 255, 255));
        jLabel72.setText("Call Duration");
        jPanel1.add(jLabel72, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 430, -1, 20));

        name_apply21.setEditable(false);
        name_apply21.setBackground(new java.awt.Color(26, 100, 162));
        name_apply21.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        name_apply21.setForeground(new java.awt.Color(255, 255, 255));
        name_apply21.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        name_apply21.setSelectionEnd(50);
        name_apply21.setSelectionStart(12);
        name_apply21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                name_apply21ActionPerformed(evt);
            }
        });
        jPanel1.add(name_apply21, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 450, 180, -1));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 190, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 160, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 70, 190, 160));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("ECF");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 30, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 510));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void exit2exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exit2exitMouseClicked
        this.setVisible(false);
    }//GEN-LAST:event_exit2exitMouseClicked

    private void exit2exitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exit2exitMouseEntered
        changecolor(exit2, new Color(69, 73, 74));
    }//GEN-LAST:event_exit2exitMouseEntered

    private void exit2exitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exit2exitMouseExited
        changecolor(exit2, new Color(52, 152, 219));
    }//GEN-LAST:event_exit2exitMouseExited

    private void name_apply7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_name_apply7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_name_apply7ActionPerformed

    private void name_apply8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_name_apply8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_name_apply8ActionPerformed

    private void name_apply9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_name_apply9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_name_apply9ActionPerformed

    private void name_apply3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_name_apply3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_name_apply3ActionPerformed

    private void name_apply4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_name_apply4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_name_apply4ActionPerformed

    private void name_apply5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_name_apply5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_name_apply5ActionPerformed

    private void name_apply10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_name_apply10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_name_apply10ActionPerformed

    private void name_apply11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_name_apply11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_name_apply11ActionPerformed

    private void name_apply12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_name_apply12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_name_apply12ActionPerformed

    private void name_apply13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_name_apply13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_name_apply13ActionPerformed

    private void name_apply14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_name_apply14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_name_apply14ActionPerformed

    private void name_apply15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_name_apply15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_name_apply15ActionPerformed

    private void name_apply16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_name_apply16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_name_apply16ActionPerformed

    private void name_apply17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_name_apply17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_name_apply17ActionPerformed

    private void name_apply18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_name_apply18ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_name_apply18ActionPerformed

    private void name_apply19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_name_apply19ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_name_apply19ActionPerformed

    private void name_apply20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_name_apply20ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_name_apply20ActionPerformed

    private void name_apply21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_name_apply21ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_name_apply21ActionPerformed

     public void changecolor(JButton hover, Color rand) {
        hover.setBackground(rand);
    }

    public void changecolor(JPanel hover, Color rand) {
        hover.setBackground(rand);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Emergency_Detail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Emergency_Detail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Emergency_Detail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Emergency_Detail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Emergency_Detail().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel exit2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField name_apply10;
    private javax.swing.JTextField name_apply11;
    private javax.swing.JTextField name_apply12;
    private javax.swing.JTextField name_apply13;
    private javax.swing.JTextField name_apply14;
    private javax.swing.JTextField name_apply15;
    private javax.swing.JTextField name_apply16;
    private javax.swing.JTextField name_apply17;
    private javax.swing.JTextField name_apply18;
    private javax.swing.JTextField name_apply19;
    private javax.swing.JTextField name_apply20;
    private javax.swing.JTextField name_apply21;
    private javax.swing.JTextField name_apply3;
    private javax.swing.JTextField name_apply4;
    private javax.swing.JTextField name_apply5;
    private javax.swing.JTextField name_apply7;
    private javax.swing.JTextField name_apply8;
    private javax.swing.JTextField name_apply9;
    // End of variables declaration//GEN-END:variables
}
