/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AmbulanceServiceSystem;

import java.awt.Button;
import java.awt.Color;
import java.sql.Driver;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JRadioButton;
import java.awt.Desktop;
import java.io.IOException;
import java.net.URI;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Proud To Be Muslims
 */
public class Login extends javax.swing.JFrame {

    ASI inst=ASI.getInst();
   CRIclass cri=CRIclass.getInst();
    public Login() {
        initComponents();
        Login.setVisible(false);
        
    }

    public String get_Radio_Button(JRadioButton  a,JRadioButton  b,JRadioButton  c)
    {
        if(a.isSelected())
        {
            return a.getText();
        }
        else if(b.isSelected())
        {
            return b.getText();
        }
        else
        {
            return c.getText();
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        signup = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        gender = new javax.swing.JTextField();
        name_apply = new javax.swing.JTextField();
        contact_Number = new javax.swing.JTextField();
        id_card = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Apply_Button = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        jRadioButton6 = new javax.swing.JRadioButton();
        Login = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel16 = new javax.swing.JLabel();
        signin = new javax.swing.JButton();
        jCheckBox1 = new javax.swing.JCheckBox();
        Mainpanel = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        setBackground(new java.awt.Color(60, 12, 44));
        setUndecorated(true);
        setResizable(false);
        setSize(new java.awt.Dimension(800, 500));
        setType(java.awt.Window.Type.POPUP);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        signup.setBackground(new java.awt.Color(255, 255, 255));
        signup.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 255));
        jLabel1.setText("Apply");
        signup.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 110, -1));

        gender.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        gender.setForeground(new java.awt.Color(102, 102, 102));
        gender.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(51, 51, 255)));
        signup.add(gender, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 220, -1));

        name_apply.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        name_apply.setForeground(new java.awt.Color(102, 102, 102));
        name_apply.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(51, 51, 255)));
        name_apply.setSelectionEnd(50);
        name_apply.setSelectionStart(12);
        name_apply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                name_applyActionPerformed(evt);
            }
        });
        signup.add(name_apply, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 220, -1));

        contact_Number.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        contact_Number.setForeground(new java.awt.Color(102, 102, 102));
        contact_Number.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(51, 51, 255)));
        signup.add(contact_Number, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 220, -1));

        id_card.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        id_card.setForeground(new java.awt.Color(102, 102, 102));
        id_card.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(51, 51, 255)));
        id_card.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        signup.add(id_card, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 220, -1));

        jLabel2.setBackground(new java.awt.Color(102, 102, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 255));
        jLabel2.setText("Gender");
        signup.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, 20));

        jLabel3.setBackground(new java.awt.Color(102, 102, 255));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 255));
        jLabel3.setText("Full Name");
        signup.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, 20));

        jLabel4.setBackground(new java.awt.Color(102, 102, 255));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 255));
        jLabel4.setText("Contact Number");
        signup.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, 20));

        jLabel5.setBackground(new java.awt.Color(102, 102, 255));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 255));
        jLabel5.setText("ID Card");
        signup.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, 20));

        Apply_Button.setBackground(new java.awt.Color(51, 51, 255));
        Apply_Button.setForeground(new java.awt.Color(255, 255, 255));
        Apply_Button.setText("Apply");
        Apply_Button.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Apply_Button.setBorderPainted(false);
        Apply_Button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Apply_Button.setFocusPainted(false);
        Apply_Button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Apply_ButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Apply_ButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Apply_ButtonMouseExited(evt);
            }
        });
        Apply_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Apply_ButtonActionPerformed(evt);
            }
        });
        signup.add(Apply_Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 310, 80, 30));

        jLabel6.setBackground(new java.awt.Color(102, 102, 255));
        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 102, 255));
        jLabel6.setText("Shift");
        signup.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, 20));

        jLabel22.setBackground(new java.awt.Color(102, 102, 255));
        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(102, 102, 255));
        jLabel22.setText("Applying for");
        signup.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, -1, 30));

        jRadioButton1.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("Night");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        signup.add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 220, 70, 30));

        jRadioButton2.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("Morning");
        jRadioButton2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(51, 51, 255)));
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });
        signup.add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 70, 30));

        jRadioButton3.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setText("Evening");
        signup.add(jRadioButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 220, 80, 30));

        jRadioButton4.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup2.add(jRadioButton4);
        jRadioButton4.setText("CTWO");
        jRadioButton4.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(51, 51, 255)));
        jRadioButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton4ActionPerformed(evt);
            }
        });
        signup.add(jRadioButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 70, 30));

        jRadioButton5.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup2.add(jRadioButton5);
        jRadioButton5.setText("Driver");
        signup.add(jRadioButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 270, 80, 30));

        jRadioButton6.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup2.add(jRadioButton6);
        jRadioButton6.setSelected(true);
        jRadioButton6.setText("EMT");
        jRadioButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton6ActionPerformed(evt);
            }
        });
        signup.add(jRadioButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 270, 70, 30));

        getContentPane().add(signup, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 70, 290, 360));

        Login.setBackground(new java.awt.Color(255, 255, 255));
        Login.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(51, 51, 255));
        jLabel14.setText("Sign in");
        Login.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 110, -1));

        jTextField5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jTextField5.setForeground(new java.awt.Color(102, 102, 102));
        jTextField5.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(51, 51, 255)));
        jTextField5.setSelectionEnd(50);
        jTextField5.setSelectionStart(12);
        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });
        Login.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 220, -1));

        jLabel15.setBackground(new java.awt.Color(102, 102, 255));
        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(102, 102, 255));
        jLabel15.setText("Password");
        Login.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, 20));

        jPasswordField1.setForeground(new java.awt.Color(102, 102, 102));
        jPasswordField1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(51, 51, 255)));
        Login.add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 220, -1));

        jLabel16.setBackground(new java.awt.Color(102, 102, 255));
        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(102, 102, 255));
        jLabel16.setText("Email");
        Login.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, 20));

        signin.setBackground(new java.awt.Color(51, 51, 255));
        signin.setForeground(new java.awt.Color(255, 255, 255));
        signin.setText("Signin");
        signin.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        signin.setBorderPainted(false);
        signin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        signin.setFocusPainted(false);
        signin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                signinMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                signinMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                signinMouseExited(evt);
            }
        });
        signin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signinActionPerformed(evt);
            }
        });
        Login.add(signin, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 282, 90, 30));

        jCheckBox1.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBox1.setText("Show Password");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        Login.add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, -1, 40));

        getContentPane().add(Login, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 70, 290, 360));

        Mainpanel.setBackground(new java.awt.Color(78, 73, 228));
        Mainpanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/google_30px.png"))); // NOI18N
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        Mainpanel.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 390, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/instagram_30px.png"))); // NOI18N
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        Mainpanel.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 390, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/twitter_30px.png"))); // NOI18N
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        Mainpanel.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 380, -1, 50));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8-ambulance-100.png"))); // NOI18N
        Mainpanel.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 40, 110, -1));

        jLabel11.setForeground(new java.awt.Color(204, 204, 204));
        jLabel11.setText("-Erich Maria");
        Mainpanel.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, -1, -1));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-doctor-100.png"))); // NOI18N
        Mainpanel.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, -1, -1));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8-employee-100.png"))); // NOI18N
        Mainpanel.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, -1, -1));

        jButton1.setBackground(new java.awt.Color(43, 43, 43));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/add_user_male_40px.png"))); // NOI18N
        jButton1.setText("Apply");
        jButton1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.setBorderPainted(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setFocusPainted(false);
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton1MouseExited(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        Mainpanel.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, 110, 40));

        jButton2.setBackground(new java.awt.Color(43, 43, 43));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/signin_30px.png"))); // NOI18N
        jButton2.setText("SignIn");
        jButton2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jButton2.setBorderPainted(false);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.setFocusPainted(false);
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton2MouseExited(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        Mainpanel.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 320, 110, 40));

        jPanel1.setBackground(new java.awt.Color(78, 73, 228));
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel1MouseExited(evt);
            }
        });

        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/exit_40px.png"))); // NOI18N

        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Exit");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel18)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        Mainpanel.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 450, 90, -1));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(204, 204, 204));
        jLabel19.setText("Ambulance Service");
        Mainpanel.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, -1, -1));

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(204, 204, 204));
        jLabel20.setText("System");
        Mainpanel.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, -1, 40));

        jLabel21.setForeground(new java.awt.Color(204, 204, 204));
        jLabel21.setText("A Hospital Alone Shows What War is.");
        Mainpanel.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, -1, -1));

        jLabel23.setFont(new java.awt.Font("MV Boli", 1, 16)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(153, 153, 153));
        jLabel23.setText("Contact Us");
        Mainpanel.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 420, 100, -1));

        getContentPane().add(Mainpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 500));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void name_applyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_name_applyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_name_applyActionPerformed

    private void Apply_ButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Apply_ButtonMouseEntered
        changecolor(Apply_Button, new Color(43, 43, 43));
    }//GEN-LAST:event_Apply_ButtonMouseEntered

    private void Apply_ButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Apply_ButtonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_Apply_ButtonMouseClicked

    private void Apply_ButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Apply_ButtonMouseExited
        changecolor(Apply_Button, new Color(51, 51, 255));
    }//GEN-LAST:event_Apply_ButtonMouseExited

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
try{         
Desktop d=Desktop.getDesktop();
         d.browse(new URI("http://www.rescue.gov.pk/"));
}
catch(Exception e){
}
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseEntered
        changecolor(jButton1, new Color(255, 51, 153));
    }//GEN-LAST:event_jButton1MouseEntered

    private void jButton1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseExited
        changecolor(jButton1, new Color(43, 43, 43));
    }//GEN-LAST:event_jButton1MouseExited

    private void jButton2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseEntered
        changecolor(jButton2, new Color(255, 51, 102));
    }//GEN-LAST:event_jButton2MouseEntered

    private void jButton2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseExited
        changecolor(jButton2, new Color(43, 43, 43));
    }//GEN-LAST:event_jButton2MouseExited

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        Login.setVisible(false);
        signup.setVisible(true);
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        Login.setVisible(true);
        signup.setVisible(false);
    }//GEN-LAST:event_jButton2MouseClicked

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
       if(jCheckBox1.isSelected())
       {
           jPasswordField1.setEchoChar((char)0);
       }
       else
       {
                      jPasswordField1.setEchoChar('*');

       }
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void signinMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signinMouseEntered
            changecolor(signin, new Color(43, 43, 43)) ;

    }//GEN-LAST:event_signinMouseEntered

    private void signinMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signinMouseExited
        changecolor(signin, new Color(51, 51, 255)) ;
    }//GEN-LAST:event_signinMouseExited

    private void jPanel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseEntered
         changecolor(jPanel1, new Color(43, 43, 43)) ;
    }//GEN-LAST:event_jPanel1MouseEntered

    private void jPanel1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseExited
       changecolor(jPanel1, new Color(78, 73, 228)) ;
    }//GEN-LAST:event_jPanel1MouseExited

    private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jPanel1MouseClicked

    private void signinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signinMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_signinMouseClicked

    private void signinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signinActionPerformed
        if(jTextField5.getText().equals("1") && jPasswordField1.getText().equals("1"))
        {
            this.setVisible(false);
            try {
                new ASI_GUI().setVisible(true);
            } catch (IOException ex) {
                Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else if(jTextField5.getText().equals("2") && jPasswordField1.getText().equals("2"))
        {
            new CTWO_GUI().setVisible(true);
        }
        else if(jTextField5.getText().equals("3") && jPasswordField1.getText().equals("3"))
        {
            new CRI().setVisible(true);
        }
else if (jTextField5.getText().equals("4")&& jPasswordField1.getText().equals("4"))
{
new EMTMain().setVisible(true);
}
    }//GEN-LAST:event_signinActionPerformed

    private void Apply_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Apply_ButtonActionPerformed
         String name=name_apply.getText();
         String contct_No=contact_Number.getText();
         long special_key=inst.Hash_Function(contct_No); 
         String id=id_card.getText();
         String pass=String.valueOf(inst.Hash_Function(id));
         String gender_q=gender.getText();
         String shift=get_Radio_Button(jRadioButton1, jRadioButton2, jRadioButton3);
         String charcter=get_Radio_Button(jRadioButton4,jRadioButton5,jRadioButton6);
         if(charcter.equals("CTWO"))
         {
             CTWOs add=new CTWOs(0, shift, name, id, contct_No, "", gender_q, special_key);
             cri.getQueue_ctwo().enqueue(add);
             JOptionPane.showMessageDialog(null, "Your Application is Submitted");
             
         }
         else if(charcter.equals("Driver"))
         {
            Drivers add=new Drivers(pass,0,shift,name, id, contct_No, "", gender_q, special_key);
            inst.getQueue_Drivers().enqueue(add);
            JOptionPane.showMessageDialog(null, "Your Application is Submitted");
         }
         else if(charcter.equals("EMT"))
         {
             
             EMTs add=new EMTs(pass,0, 0, shift, name, id, contct_No, "", gender_q, special_key);
             inst.getQueue_EMTs().enqueue(add);   
             JOptionPane.showMessageDialog(null, "Your Application is Submitted");
         }

         
    }//GEN-LAST:event_Apply_ButtonActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton4ActionPerformed

    private void jRadioButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton6ActionPerformed

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        // TODO add your handling code here:
try{         
Desktop d=Desktop.getDesktop();
         d.browse(new URI("https://www.instagram.com/pac__saqi/"));
}
catch(Exception e){
}
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        // TODO add your handling code here:
try{         
Desktop d=Desktop.getDesktop();
         d.browse(new URI("https://twitter.com/home"));
}
catch(Exception e){
}
    }//GEN-LAST:event_jLabel9MouseClicked

    public void changecolor(JButton hover, Color rand) {
        hover.setBackground(rand);
    }
     public void changecolor(JPanel hover, Color rand) {
        hover.setBackground(rand);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Apply_Button;
    private javax.swing.JPanel Login;
    private javax.swing.JPanel Mainpanel;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JTextField contact_Number;
    private javax.swing.JTextField gender;
    private javax.swing.JTextField id_card;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField name_apply;
    private javax.swing.JButton signin;
    private javax.swing.JPanel signup;
    // End of variables declaration//GEN-END:variables
}
